version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80"

packages: [php8.1-curl, php8.1-http, php8.1-raphf, inotify-tools, poppler-utils]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "npm install"


  init:
    - "sudo mkdir -p /data"
    - "sudo chmod -R 777 /data"


  dev:
    - "sudo phpdismod xdebug"
    - "sudo service apache2 restart"

  test:


